// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGseiNFPbMEsBt4CX-mDjGX7GAbbO4xJ4',
    appId: '1:1054048280684:web:052bfec9b8e08c8a07f849',
    messagingSenderId: '1054048280684',
    projectId: 'gymsta-d2a7d',
    authDomain: 'gymsta-d2a7d.firebaseapp.com',
    storageBucket: 'gymsta-d2a7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkE_gl23ZeUsBnKr2fTOJMOWuFMDW11CM',
    appId: '1:1054048280684:android:3085f4a07ed8237207f849',
    messagingSenderId: '1054048280684',
    projectId: 'gymsta-d2a7d',
    storageBucket: 'gymsta-d2a7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_UXBqPbR5gkwSHpLDk34ds-PJwbnlHWM',
    appId: '1:1054048280684:ios:fddb8f2f4e2559f807f849',
    messagingSenderId: '1054048280684',
    projectId: 'gymsta-d2a7d',
    storageBucket: 'gymsta-d2a7d.appspot.com',
    iosClientId: '1054048280684-3tvc3n47hkqq9m37eqdsdl5r2g8f28ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymsta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_UXBqPbR5gkwSHpLDk34ds-PJwbnlHWM',
    appId: '1:1054048280684:ios:fddb8f2f4e2559f807f849',
    messagingSenderId: '1054048280684',
    projectId: 'gymsta-d2a7d',
    storageBucket: 'gymsta-d2a7d.appspot.com',
    iosClientId: '1054048280684-3tvc3n47hkqq9m37eqdsdl5r2g8f28ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymsta',
  );
}
